service: let-me-know-rest-api # NOTE: update this with your service name

custom:
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'eu-west-1'}
  config: ${file(./config.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  environment:
    NODE_ENV: ${self:custom.stage}
    REGION: ${self:custom.region}

resources:
  Resources:
    ContactPoints:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamoDb.tables.ContactPoints.tableName}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPoints.userId}
            AttributeType: S
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPoints.cpId}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPoints.userId}
            KeyType: HASH
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPoints.cpId}
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: ${self:custom.config.dynamoDb.tables.ContactPoints.globalIndexName}
            KeySchema:
              - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPoints.cpId}
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            Projection:
              ProjectionType: "ALL"
    DiscussionMessages:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.tableName}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.discussionId}
            AttributeType: S
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.createdTime}
            AttributeType: N
        KeySchema:
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.discussionId}
            KeyType: HASH
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.createdTime}
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Discussions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamoDb.tables.Discussions.tableName}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.cpId}
            AttributeType: S
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.userId}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.cpId}
            KeyType: HASH
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.userId}
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
functions:
  letMeKnowWeb:
    handler: dist/webHandler.letMeKnow
    package:
      exclude:
        - src
        - test
    events:
      - http:
          path: /rest/discussion/{cpid}
          method: get
          cors: true
      - http:
          path: /rest/discussion/{cpid}
          method: put
          cors: true
  letMeKnow:
    handler: dist/handler.letMeKnow
    package:
      exclude:
        - src
        - test
    events:
      - http:
          path: /rest/{pathsuffix+}
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.config.cognito.arn}
      - http:
          path: /rest/{pathsuffix+}
          method: put
          cors: true
          authorizer:
            arn: ${self:custom.config.cognito.arn}
      - http:
          path: /rest/{pathsuffix+}
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.config.cognito.arn}
