service: let-me-know-rest-api # NOTE: update this with your service name

custom:
  stage: ${opt:stage,'dev'}
  region: ${opt:region,'eu-west-1'}
  config: ${file(./config.json)}
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  environment:
    NODE_ENV: ${self:custom.stage}
    REGION: ${self:custom.region}
resources:
  Resources:
    ContactPoints:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamoDb.tables.ContactPoints.tableName}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPoints.fields.cpId}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPoints.fields.cpId}
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ContactPointsUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamoDb.tables.ContactPointsUsers.tableName}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPointsUsers.fields.cpId}
            AttributeType: S
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPointsUsers.fields.userId}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPointsUsers.fields.userId}
            KeyType: HASH
          - AttributeName: ${self:custom.config.dynamoDb.tables.ContactPointsUsers.fields.cpId}
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    DiscussionMessages:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.tableName}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.fields.discussionId}
            AttributeType: S
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.fields.createdTime}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.fields.discussionId}
            KeyType: HASH
          - AttributeName: ${self:custom.config.dynamoDb.tables.DiscussionMessages.fields.createdTime}
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    Discussions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.config.dynamoDb.tables.Discussions.tableName}-${self:custom.stage}
        AttributeDefinitions:
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.fields.cpId}
            AttributeType: S
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.fields.discussionId}
            AttributeType: S
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.fields.connectorId}
            AttributeType: S
        KeySchema:
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.fields.cpId}
            KeyType: HASH
          - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.fields.discussionId}
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: ${self:custom.config.dynamoDb.tables.Discussions.indexName}
            KeySchema:
              - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.fields.cpId}
                KeyType: HASH
              - AttributeName: ${self:custom.config.dynamoDb.tables.Discussions.fields.connectorId}
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
functions:
  letMeKnow:
    handler: dist/handler.letMeKnow
    package:
      exclude:
        - src
        - test
    events:
      - http:
          path: /rest/{pathsuffix+}
          method: get
          cors: true
          authorizer:
            arn: ${self:custom.config.cognito.arn}
      - http:
          path: /rest/{pathsuffix+}
          method: put
          cors: true
          authorizer:
            arn: ${self:custom.config.cognito.arn}
      - http:
          path: /rest/{pathsuffix+}
          method: post
          cors: true
          authorizer:
            arn: ${self:custom.config.cognito.arn}